### ISSUE TITLE
Research reading taught in NY state in 4th Grade Reading

### ISSUE THREAD

**Issue by ajman1101** [FOSSRIT/point-and-click-arthur#1]
We need someone to work on what knowledge 4th graders have in Reading. This will help the team determine how verbose the story can be and what kind of language can be used.

**Comment by ajman1101** [comment]
Here's a link to the NY State Reading Standards: http://www.p12.nysed.gov/ciai/ela/elacore.pdf

**Comment by dtgay** [comment]
I'm looking into this right now.
