### ISSUE TITLE
Having to kill the process when exiting the game

### ISSUE THREAD

**Issue by nmb7895** [FOSSRIT/point-and-click-arthur#11]
This was working in prototype 1, but the new prototype has the error again. When quitting pygame the application crashes and has to be killed manually. This needs to be addressed ASAP, as it slows down testing.

**Comment by dtgay** [comment]
Also addressing this tomorrow!

**Comment by dtgay** [comment]
After debugging for a while, I have decided to refactor the code, which may solve this problem as well as others.

**Comment by dtgay** [comment]
Made some progress I think, but quitting now leads to a segmentation fault...
