### ISSUE TITLE
Window size too large!

### ISSUE THREAD

**Issue by dtgay** [FOSSRIT/point-and-click-arthur#12]
When I started working on bugs this weekend, I discovered that the window size was set to 1200x900, which is too large for my resolution! I may play around with these values on my branches for testing purposes on my laptop, but the screen/background/gui does not resize (obviously), so everything is cropped off.

Any solution to this besides shrinking everything? I'm not sure what extent of modifaction you'll have to go through. I know that the OLPC resolution is 1200x900, but it's not fitting on my screen, which has a resolution of 1366x768.

I am using Fedora, so I can easily use the alt key to drag the window around my screen if I keep the size at 1200x900 for accuracy, and this isn't really a huge problem.

**Comment by ajman1101** [comment]
Lines 6&7 determine the window's width and height, I would change those values and you should be fine.

**Comment by dtgay** [comment]
Yeah, changing the variables isn't a problem, but the rest of the content doesn't shrink with it. I'm fine draging the window about, though. :)
