### ISSUE TITLE
Get Sound!

### ISSUE THREAD

**Issue by ajman1101** [FOSSRIT/point-and-click-arthur#2]
We need sound for our game! If we can find open source sound effects and open source medieval sounds that would be great!

**Comment by dtgay** [comment]
As I added to the readme in the david-apr-18 branch, http://www.freesound.org/ should be able to help us here

**Comment by dtgay** [comment]
I added a few sounds and a music track, but we'll add more as the game develops.

**Comment by ajman1101** [comment]
found all needed sounds
