### ISSUE TITLE
ART

### ISSUE THREAD

**Issue by ajman1101** [FOSSRIT/point-and-click-arthur#3]
The team needs to determine an art style and someone to make this glorious art!

**Comment by dtgay** [comment]
Worth noting -- if we did stick-person illustrations, we could draw everything ourselves. ;)

**Comment by dtgay** [comment]
As I added to the readme in the david-apr-18 branch, http://openclipart.org/ might have some of what we need.

**Comment by ajman1101** [comment]
The team has made/found all the art they will need. Thanks for the help!
